all: reader_Aprocess writer_Bprocess

reader_Aprocess:
	gcc -o reader_Aprocess reader_Aprocess.c

writer_Bprocess:
	gcc -o writer_Bprocess writer_Bprocess.c

clean:
	rm writer_Bprocess reader_Aprocess
